export type ObstaclePattern = {
    row: number;
    col: number;
}

const pattern_1: ObstaclePattern[] = [
    { row: 0, col: 9 },
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 1, col: 3 },
    { row: 1, col: 5 },
    { row: 1, col: 6 },
    { row: 1, col: 7 },
    { row: 1, col: 9 },
    { row: 2, col: 3 },
    { row: 2, col: 3 },
    { row: 2, col: 7 },
    { row: 2, col: 9 },
    { row: 3, col: 1 },
    { row: 3, col: 2 },
    { row: 3, col: 3 },
    { row: 3, col: 4 },
    { row: 3, col: 5 },
    { row: 3, col: 7 },
    { row: 3, col: 9 },
    { row: 4, col: 1 },
    { row: 4, col: 7 },
    { row: 4, col: 9 },
    { row: 5, col: 0 },
    { row: 5, col: 1 },
    { row: 5, col: 3 },
    { row: 5, col: 4 },
    { row: 5, col: 5 },
    { row: 5, col: 5 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
    { row: 5, col: 7 },
    { row: 7, col: 5 },
    { row: 8, col: 5 },
    { row: 6, col: 3 },
    { row: 6, col: 7 },
    { row: 6, col: 8 },
    { row: 6, col: 9 },
    { row: 7, col: 1 },
    { row: 7, col: 2 },
    { row: 7, col: 3 },
    { row: 7, col: 4 },
    { row: 7, col: 7 },
    { row: 8, col: 1 },
    { row: 8, col: 7 },
    { row: 8, col: 9 },
    { row: 8, col: 10 },
    { row: 9, col: 1 },
    { row: 9, col: 2 },
    { row: 9, col: 3 },
    { row: 9, col: 5 },
    { row: 10, col: 5 },
    { row: 9, col: 7 },
  ];
  
  const pattern_2: ObstaclePattern[] = [
    { row: 0, col: 7 },
    { row: 1, col: 0 },
    { row: 1, col: 1 },
    { row: 1, col: 3 },
    { row: 1, col: 5 },
    { row: 1, col: 8 },
    { row: 1, col: 9 },
    { row: 1, col: 7 },
    { row: 2, col: 3 },
    { row: 3, col: 1 },
    { row: 3, col: 2 },
    { row: 3, col: 3 },
    { row: 3, col: 4 },
    { row: 3, col: 5 },
    { row: 3, col: 7 },
    { row: 3, col: 8 },
    { row: 3, col: 9 },
    { row: 4, col: 1 },
    { row: 4, col: 5 },
    { row: 4, col: 7 },
    { row: 4, col: 9 },
    { row: 5, col: 1 },
    { row: 5, col: 3 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
    { row: 5, col: 7 },
    { row: 5, col: 9 },
    { row: 5, col: 10 },
    { row: 6, col: 1 },
    { row: 6, col: 3 },
    { row: 6, col: 9 },
    { row: 7, col: 3 },
    { row: 7, col: 4 },
    { row: 7, col: 5 },
    { row: 7, col: 7 },
    { row: 8, col: 1 },
    { row: 8, col: 3 },
    { row: 9, col: 2 },
    { row: 8, col: 7 },
    { row: 8, col: 9 },
    { row: 9, col: 1 },
    { row: 9, col: 3 },
    { row: 9, col: 5 },
    { row: 9, col: 7 },
    { row: 9, col: 6 },
    { row: 9, col: 9 },
    { row: 10, col: 3 },
    { row: 10, col: 9 },
  ];
  
  const pattern_3: ObstaclePattern[] = [
    { row: 0, col: 5 },
    { row: 1, col: 0 },
    { row: 1, col: 1 },
    { row: 1, col: 3 },
    { row: 1, col: 5 },
    { row: 1, col: 6 },
    { row: 1, col: 7 },
    { row: 1, col: 8 },
    { row: 1, col: 9 },
    { row: 2, col: 3 },
    { row: 2, col: 7 },
    { row: 3, col: 1 },
    { row: 3, col: 2 },
    { row: 3, col: 3 },
    { row: 3, col: 4 },
    { row: 3, col: 5 },
    { row: 3, col: 7 },
    { row: 3, col: 9 },
    { row: 4, col: 3 },
    { row: 4, col: 5 },
    { row: 4, col: 7 },
    { row: 4, col: 9 },
    { row: 5, col: 1 },
    { row: 5, col: 3 },
    { row: 5, col: 5 },
    { row: 5, col: 7 },
    { row: 5, col: 9 },
    { row: 5, col: 10 },
    { row: 6, col: 1 },
    { row: 6, col: 3 },
    { row: 6, col: 5 },
    { row: 6, col: 7 },
    { row: 7, col: 1 },
    { row: 7, col: 3 },
    { row: 7, col: 5 },
    { row: 7, col: 7 },
    { row: 7, col: 8 },
    { row: 7, col: 9 },
    { row: 8, col: 1 },
    { row: 8, col: 3 },
    { row: 9, col: 1 },
    { row: 9, col: 3 },
    { row: 9, col: 4 },
    { row: 9, col: 5 },
    { row: 9, col: 6 },
    { row: 9, col: 7 },
    { row: 9, col: 8 },
    { row: 9, col: 9 },
    { row: 10, col: 1 },
    { row: 10, col: 7 }
  ]
  
  const pattern_4: ObstaclePattern[] = [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 1, col: 3 },
    { row: 1, col: 4 },
    { row: 1, col: 5 },
    { row: 1, col: 6 },
    { row: 1, col: 7 },
    { row: 1, col: 8 },
    { row: 1, col: 9 },
    { row: 1, col: 10 },
    { row: 3, col: 0 },
    { row: 3, col: 1 },
    { row: 3, col: 2 },
    { row: 3, col: 3 },
    { row: 3, col: 4 },
    { row: 3, col: 5 },
    { row: 3, col: 6 },
    { row: 3, col: 7 },
    { row: 3, col: 8 },
    { row: 3, col: 9 },
    { row: 5, col: 1 },
    { row: 5, col: 2 },
    { row: 5, col: 3 },
    { row: 5, col: 4 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
    { row: 5, col: 7 },
    { row: 5, col: 8 },
    { row: 5, col: 9 },
    { row: 5, col: 10 },
    { row: 7, col: 1 },
    { row: 7, col: 2 },
    { row: 7, col: 3 },
    { row: 7, col: 4 },
    { row: 7, col: 5 },
    { row: 7, col: 6 },
    { row: 7, col: 7 },
    { row: 7, col: 8 },
    { row: 7, col: 9 },
    { row: 8, col: 5 },
    { row: 9, col: 0 },
    { row: 9, col: 1 },
    { row: 9, col: 2 },
    { row: 9, col: 3 },
    { row: 9, col: 5 },
    { row: 9, col: 6 },
    { row: 9, col: 7 },
    { row: 9, col: 8 },
    { row: 9, col: 9 },
    { row: 9, col: 10 },
  ]
  
  const pattern_5: ObstaclePattern[] = [
    { row: 0, col: 1 },
    { row: 1, col: 1 },
    { row: 2, col: 1 },
    { row: 3, col: 1 },
    { row: 4, col: 1 },
    { row: 5, col: 1 },
    { row: 7, col: 1 },
    { row: 8, col: 1 },
    { row: 9, col: 1 },
    { row: 7, col: 2 },
    { row: 1, col: 3 },
    { row: 2, col: 3 },
    { row: 3, col: 3 },
    { row: 4, col: 3 },
    { row: 5, col: 3 },
    { row: 6, col: 3 },
    { row: 7, col: 3 },
    { row: 9, col: 3 },
    { row: 10, col: 3 },
    { row: 7, col: 4 },
    { row: 1, col: 5 },
    { row: 2, col: 5 },
    { row: 3, col: 5 },
    { row: 4, col: 5 },
    { row: 5, col: 5 },
    { row: 7, col: 5 },
    { row: 8, col: 5 },
    { row: 9, col: 5 },
    { row: 10, col: 5 },
    { row: 5, col: 6 },
    { row: 0, col: 7 },
    { row: 1, col: 7 },
    { row: 2, col: 7 },
    { row: 3, col: 7 },
    { row: 5, col: 7 },
    { row: 6, col: 7 },
    { row: 7, col: 7 },
    { row: 8, col: 7 },
    { row: 9, col: 7 },
    { row: 1, col: 8 },
    { row: 5, col: 8 },
    { row: 1, col: 9 },
    { row: 3, col: 9 },
    { row: 4, col: 9 },
    { row: 5, col: 9 },
    { row: 7, col: 9 },
    { row: 8, col: 9 },
    { row: 9, col: 9 },
    { row: 10, col: 9 },
    { row: 5, col: 10 },
    
    
  ]
  
  // Массив различных паттернов препятствий для поля 11x11
  export const obstaclePatterns: ObstaclePattern[][] = [
    pattern_1,
    pattern_2,
    pattern_3,
    pattern_4,
    pattern_5,
  ];
  
  // Функция для получения случайного паттерна
  export const getRandomPattern = (): ObstaclePattern[] => {
    const randomIndex = Math.floor(Math.random() * obstaclePatterns.length);
    return obstaclePatterns[randomIndex];
  }; 